In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/application_train.csv")

df.head()

,Unnamed: 0,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
0,0,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,278621
1,1,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,139008
2,2,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,138348
3,3,0,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,64140
4,4,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,219374

In [2]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().mean()*100)
})

missing = missing[missing["Missing Values"]>0]
missing.sort_values("Percentage", ascending=False).head(20)

                          Missing Values  Percentage
COMMONAREA_MEDI                   171930   69.887687
COMMONAREA_MODE                   171930   69.887687
COMMONAREA_AVG                    171930   69.887687
NONLIVINGAPARTMENTS_MODE          170869   69.456402
NONLIVINGAPARTMENTS_MEDI          170869   69.456402
NONLIVINGAPARTMENTS_AVG           170869   69.456402
FONDKAPREMONT_MODE                168287   68.406847
LIVINGAPARTMENTS_AVG              168197   68.370263
LIVINGAPARTMENTS_MEDI             168197   68.370263
LIVINGAPARTMENTS_MODE             168197   68.370263
FLOORSMIN_MEDI                    166955   67.865403
FLOORSMIN_MODE                    166955   67.865403
FLOORSMIN_AVG                     166955   67.865403
YEARS_BUILD_MODE                  163684   66.535777
YEARS_BUILD_MEDI                  163684   66.535777
YEARS_BUILD_AVG                   163684   66.535777
OWN_CAR_AGE                       162188   65.927669
LANDAREA_AVG                      146130   59.400266
LANDAREA_MEDI                     146130   59.400266
LANDAREA_MODE                     146130   59.400266

In [3]:
threshold = 50

drop_cols = missing[
    missing["Percentage"] > threshold
].index

len(drop_cols)

41

In [4]:
df = df.drop(columns=drop_cols)

print(df.shape)

(246009, 82)

In [5]:
numeric_cols = df.select_dtypes(include=["int64","float64"]).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [6]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

C:\Users\hp\AppData\Local\Temp\ipykernel_18668\3309253727.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [7]:
df.isnull().sum().sum()

np.int64(0)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.to_csv(
    "../data/processed/application_train_cleaned.csv",
    index=False
)